# Uncomment the next line to define a global platform for your project
 platform :ios, '12.2'

target 'SoulPartner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoulPartner
  pod 'MessageKit'
  pod 'MessageInputBar'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'lottie-ios'
end
