# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vibration' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vibration
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'VibrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VibrationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
